### PR TITLE
Badges visible on `UserCard`

### PR DESCRIPTION
**Pull request by datlechin**
Issue #9

Screenshot from 2022-06-17 16-56-57
Screenshot from 2022-06-17 16-56-35

### CODE REVIEW

**Comment by datlechin** [comment]
**New**

image


Hi @jaspervriends, could you review them?
Hope it soon merged,

**Comment by iamdarkle** [comment]
Very cool! great PR, is this per badge (the user selects which badges are shown) or does it show all the badges the user has?

**Comment by datlechin** [comment]
> Very cool! great PR, is this per badge (the user selects which badges are shown) or does it show all the badges the user has?

It shows all the badges that the user has

**Comment by jaspervriends** [comment]
@datlechin That latest update was actually a question I wanted to ask. Great you have implemented that (and everything else, very cool feature!).

I think I agree with @iamdarkle , would be great if a user can select what badges there are visible in the user-card. I think adding a `in_user_card` (boolean) column to the `badge_user` table would satisfy. Is it possible for you to add a 'max visible badges in card' setting, which might default to 4 or 5 badges? Otherwise, if a user would have 50 badges in their card. If the limit has been reached, a simple 'Plus 5 more badges' link would be added or something like that.

If there are no badges selected by the user, it would be cool if they were auto selected by ranking them on their order (or highest badge points, as these will be added in the future).

I'm currently working on the Support extension at the moment, so if there are any questions, let me know!

**Comment by datlechin** [comment]
Hmm, I have no idea about the feature that user can select what badges. 
I'm keep learning, maybe in future ^^

**Comment by datlechin** [comment]
**Latest changes**

Screenshot from 2022-06-17 21-43-06
Screenshot from 2022-06-17 21-43-25

**Comment by jaspervriends** [comment]
Thanks for your contribution! Really cool! I'll merge it for a release later today or tomorrow :)

**Pull request merged**
